/**
 * Project statistics — AUTO-GENERATED by tools/gen-project-stats.mjs
 * Do not edit by hand. Do not invent numbers.
 * Regenerated: 2026-09-04
 */

/** @type {Readonly<typeof PROJECT_STATS>} */
export const PROJECT_STATS = Object.freeze({
  "generatedAt": "2026-09-04",
  "stages": 4,
  "jsModules": 60,
  "jsLinesOfCode": 43257,
  "gfxModules": 11,
  "physicsModules": 4,
  "audioModules": 9,
  "trackModules": 17,
  "qaScripts": 128,
  "toolsScripts": 134,
  "docs": 28,
  "glbAssets": 85,
  "vendorModules": 6,
  "cars": 3
});
